<?php

use Atin\LaravelCashierShop\Enums\CurrencyDecimalType;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('currencies', function (Blueprint $table) {
            $table->id();
            $table->char('iso_code', 3)->unique();
            $table->string('decimal_type');
            $table->integer('min_charge_amount')->nullable();
            $table->json('country_codes')->nullable();
            $table->timestamps();
        });

        $currencies = [
            [
                'iso_code' => 'USD',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => 50,
                'country_codes' => json_encode(['as', 'io', 'ec', 'sv', 'gu', 'mh', 'fm', 'mp', 'pw', 'pr', 'tl', 'tc', 'us', 'um', 'vg', 'vi']),
            ],
            [
                'iso_code' => 'AED',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => 200,
                'country_codes' => json_encode(['ae']),
            ],
            [
                'iso_code' => 'AFN',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['af']),
            ],
            [
                'iso_code' => 'ALL',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['al']),
            ],
            [
                'iso_code' => 'AMD',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['am']),
            ],
            [
                'iso_code' => 'ANG',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['an']),
            ],
            [
                'iso_code' => 'AOA',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['ao']),
            ],
            [
                'iso_code' => 'ARS',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['ar']),
            ],
            [
                'iso_code' => 'AUD',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => 50,
                'country_codes' => json_encode(['au', 'cx', 'cc', 'hm', 'ki', 'nr', 'nf', 'tv']),
            ],
            [
                'iso_code' => 'AWG',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['aw']),
            ],
            [
                'iso_code' => 'AZN',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['az']),
            ],
            [
                'iso_code' => 'BAM',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['ba']),
            ],
            [
                'iso_code' => 'BBD',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['bb']),
            ],
            [
                'iso_code' => 'BDT',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['bd']),
            ],
            [
                'iso_code' => 'BGN',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => 100,
                'country_codes' => json_encode(['bg']),
            ],
            [
                'iso_code' => 'BIF',
                'decimal_type' => CurrencyDecimalType::ZERO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['bi']),
            ],
            [
                'iso_code' => 'BMD',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['bm']),
            ],
            [
                'iso_code' => 'BND',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['bn']),
            ],
            [
                'iso_code' => 'BOB',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['bo']),
            ],
            [
                'iso_code' => 'BRL',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => 50,
                'country_codes' => json_encode(['br']),
            ],
            [
                'iso_code' => 'BSD',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['bs']),
            ],
            [
                'iso_code' => 'BWP',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['bw']),
            ],
            [
                'iso_code' => 'BYN',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['by']),
            ],
            [
                'iso_code' => 'BZD',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['bz']),
            ],
            [
                'iso_code' => 'CAD',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => 50,
                'country_codes' => json_encode(['ca']),
            ],
            [
                'iso_code' => 'CDF',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['cd']),
            ],
            [
                'iso_code' => 'CHF',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => 50,
                'country_codes' => json_encode(['li', 'ch']),
            ],
            [
                'iso_code' => 'CLP',
                'decimal_type' => CurrencyDecimalType::ZERO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['cl']),
            ],
            [
                'iso_code' => 'CNY',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['cn']),
            ],
            [
                'iso_code' => 'COP',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['co']),
            ],
            [
                'iso_code' => 'CRC',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['cr']),
            ],
            [
                'iso_code' => 'CVE',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['cv']),
            ],
            [
                'iso_code' => 'CZK',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => 1500,
                'country_codes' => json_encode(['cz']),
            ],
            [
                'iso_code' => 'DJF',
                'decimal_type' => CurrencyDecimalType::ZERO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['dj']),
            ],
            [
                'iso_code' => 'DKK',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => 250,
                'country_codes' => json_encode(['dk', 'fo', 'gl']),
            ],
            [
                'iso_code' => 'DOP',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['do']),
            ],
            [
                'iso_code' => 'DZD',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['dz']),
            ],
            [
                'iso_code' => 'EGP',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['eg']),
            ],
            [
                'iso_code' => 'ETB',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['et']),
            ],
            [
                'iso_code' => 'EUR',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => 50,
                'country_codes' => json_encode(['ax', 'ad', 'at', 'be', 'cy', 'ee', 'fi', 'fr', 'gf', 'tf', 'de', 'gr', 'gp', 'va', 'ie', 'it', 'lv', 'lu', 'mt', 'mq', 'yt', 'mc', 'nl', 'pt', 're', 'pm', 'sm', 'me', 'sk', 'si', 'es']),
            ],
            [
                'iso_code' => 'FJD',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['fj']),
            ],
            [
                'iso_code' => 'FKP',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['fk']),
            ],
            [
                'iso_code' => 'GBP',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => 30,
                'country_codes' => json_encode(['gg', 'im', 'je', 'gs', 'gb']),
            ],
            [
                'iso_code' => 'GEL',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['ge']),
            ],
            [
                'iso_code' => 'GIP',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['gi']),
            ],
            [
                'iso_code' => 'GMD',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['gm']),
            ],
            [
                'iso_code' => 'GNF',
                'decimal_type' => CurrencyDecimalType::ZERO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['gn']),
            ],
            [
                'iso_code' => 'GTQ',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['gt']),
            ],
            [
                'iso_code' => 'GYD',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['gy']),
            ],
            [
                'iso_code' => 'HKD',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => 400,
                'country_codes' => json_encode(['hk']),
            ],
            [
                'iso_code' => 'HNL',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['hn']),
            ],
            [
                'iso_code' => 'HTG',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['ht']),
            ],
            [
                'iso_code' => 'HUF',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => 17500,
                'country_codes' => json_encode(['hu']),
            ],
            [
                'iso_code' => 'IDR',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['id']),
            ],
            [
                'iso_code' => 'ILS',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['il', 'ps']),
            ],
            [
                'iso_code' => 'INR',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => 50,
                'country_codes' => json_encode(['in']),
            ],
            [
                'iso_code' => 'ISK',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['is']),
            ],
            [
                'iso_code' => 'JMD',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['jm']),
            ],
            [
                'iso_code' => 'JPY',
                'decimal_type' => CurrencyDecimalType::ZERO_DECIMAL,
                'min_charge_amount' => 50,
                'country_codes' => json_encode(['jp']),
            ],
            [
                'iso_code' => 'KES',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['ke']),
            ],
            [
                'iso_code' => 'KGS',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['kg']),
            ],
            [
                'iso_code' => 'KHR',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['kh']),
            ],
            [
                'iso_code' => 'KMF',
                'decimal_type' => CurrencyDecimalType::ZERO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['km']),
            ],
            [
                'iso_code' => 'KRW',
                'decimal_type' => CurrencyDecimalType::ZERO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['kr']),
            ],
            [
                'iso_code' => 'KYD',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['ky']),
            ],
            [
                'iso_code' => 'KZT',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['kz']),
            ],
            [
                'iso_code' => 'LAK',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['la']),
            ],
            [
                'iso_code' => 'LBP',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['lb']),
            ],
            [
                'iso_code' => 'LKR',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['lk']),
            ],
            [
                'iso_code' => 'LRD',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['lr']),
            ],
            [
                'iso_code' => 'LSL',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['ls']),
            ],
            [
                'iso_code' => 'MAD',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['ma', 'eh']),
            ],
            [
                'iso_code' => 'MDL',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['md']),
            ],
            [
                'iso_code' => 'MGA',
                'decimal_type' => CurrencyDecimalType::ZERO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['mg']),
            ],
            [
                'iso_code' => 'MKD',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['mk']),
            ],
            [
                'iso_code' => 'MMK',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['mm']),
            ],
            [
                'iso_code' => 'MNT',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['mn']),
            ],
            [
                'iso_code' => 'MOP',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['mo']),
            ],
            [
                'iso_code' => 'MUR',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['mu']),
            ],
            [
                'iso_code' => 'MVR',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['mv']),
            ],
            [
                'iso_code' => 'MWK',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['mw']),
            ],
            [
                'iso_code' => 'MXN',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => 1000,
                'country_codes' => json_encode(['mx']),
            ],
            [
                'iso_code' => 'MYR',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => 200,
                'country_codes' => json_encode(['my']),
            ],
            [
                'iso_code' => 'MZN',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['mz']),
            ],
            [
                'iso_code' => 'NAD',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['na']),
            ],
            [
                'iso_code' => 'NGN',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['ng']),
            ],
            [
                'iso_code' => 'NIO',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['ni']),
            ],
            [
                'iso_code' => 'NOK',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => 300,
                'country_codes' => json_encode(['bv', 'no', 'sj']),
            ],
            [
                'iso_code' => 'NPR',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['np']),
            ],
            [
                'iso_code' => 'NZD',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => 50,
                'country_codes' => json_encode(['ck', 'nz', 'nu', 'pn', 'tk']),
            ],
            [
                'iso_code' => 'PAB',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['pa']),
            ],
            [
                'iso_code' => 'PEN',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['pe']),
            ],
            [
                'iso_code' => 'PGK',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['pg']),
            ],
            [
                'iso_code' => 'PHP',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['ph']),
            ],
            [
                'iso_code' => 'PKR',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['pk']),
            ],
            [
                'iso_code' => 'PLN',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => 200,
                'country_codes' => json_encode(['pl']),
            ],
            [
                'iso_code' => 'PYG',
                'decimal_type' => CurrencyDecimalType::ZERO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['py']),
            ],
            [
                'iso_code' => 'QAR',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['qa']),
            ],
            [
                'iso_code' => 'RON',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => 200,
                'country_codes' => json_encode(['ro']),
            ],
            [
                'iso_code' => 'RSD',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['rs']),
            ],
            [
                'iso_code' => 'RUB',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['ru']),
            ],
            [
                'iso_code' => 'RWF',
                'decimal_type' => CurrencyDecimalType::ZERO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['rw']),
            ],
            [
                'iso_code' => 'SAR',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['sa']),
            ],
            [
                'iso_code' => 'SBD',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['sb']),
            ],
            [
                'iso_code' => 'SCR',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['sc']),
            ],
            [
                'iso_code' => 'SEK',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => 300,
                'country_codes' => json_encode(['se']),
            ],
            [
                'iso_code' => 'SGD',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => 50,
                'country_codes' => json_encode(['sg']),
            ],
            [
                'iso_code' => 'SHP',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['sh']),
            ],
            [
                'iso_code' => 'SLE',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['sl']),
            ],
            [
                'iso_code' => 'SOS',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['so']),
            ],
            [
                'iso_code' => 'SRD',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['sr']),
            ],
            [
                'iso_code' => 'STD',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['st']),
            ],
            [
                'iso_code' => 'SZL',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['sz']),
            ],
            [
                'iso_code' => 'THB',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => 1000,
                'country_codes' => json_encode(['th']),
            ],
            [
                'iso_code' => 'TJS',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['tj']),
            ],
            [
                'iso_code' => 'TOP',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['to']),
            ],
            [
                'iso_code' => 'TRY',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['tr']),
            ],
            [
                'iso_code' => 'TTD',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['tt']),
            ],
            [
                'iso_code' => 'TWD',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['tw']),
            ],
            [
                'iso_code' => 'TZS',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['tz']),
            ],
            [
                'iso_code' => 'UAH',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['ua']),
            ],
            [
                'iso_code' => 'UGX',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['ug']),
            ],
            [
                'iso_code' => 'UYU',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['uy']),
            ],
            [
                'iso_code' => 'UZS',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['uz']),
            ],
            [
                'iso_code' => 'VND',
                'decimal_type' => CurrencyDecimalType::ZERO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['vn']),
            ],
            [
                'iso_code' => 'VUV',
                'decimal_type' => CurrencyDecimalType::ZERO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['vu']),
            ],
            [
                'iso_code' => 'WST',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['ws']),
            ],
            [
                'iso_code' => 'XAF',
                'decimal_type' => CurrencyDecimalType::ZERO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['cm', 'cf', 'td', 'cg', 'gq', 'ga']),
            ],
            [
                'iso_code' => 'XCD',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['ai', 'ag', 'dm', 'gd', 'ms', 'kn', 'lc', 'vc']),
            ],
            [
                'iso_code' => 'XOF',
                'decimal_type' => CurrencyDecimalType::ZERO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['bj', 'bf', 'ci', 'gw', 'ml', 'ne', 'sn', 'tg']),
            ],
            [
                'iso_code' => 'XPF',
                'decimal_type' => CurrencyDecimalType::ZERO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['pf', 'nc', 'wf']),
            ],
            [
                'iso_code' => 'YER',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['ye']),
            ],
            [
                'iso_code' => 'ZAR',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['za']),
            ],
            [
                'iso_code' => 'ZMW',
                'decimal_type' => CurrencyDecimalType::TWO_DECIMAL,
                'min_charge_amount' => null,
                'country_codes' => json_encode(['zm']),
            ],
        ];

        DB::table('currencies')->insert($currencies);
    }

    public function down(): void
    {
        Schema::dropIfExists('currencies');
    }
};
