<?php

return [

    'country_to_currency' => [
        'us' => 'USD',
        'ca' => 'CAD',
        'gb' => 'GBP',
        'se' => 'SEK',
        'de' => 'EUR',
        'es' => 'EUR',
        'pt' => 'EUR',
        'fr' => 'EUR',
        'it' => 'EUR',
        'fi' => 'EUR',
        'be' => 'EUR',
        'at' => 'EUR',
        'gr' => 'EUR',
        'ie' => 'EUR',
        'sk' => 'EUR',
        'lt' => 'EUR',
        'lv' => 'EUR',
        'ee' => 'EUR',
        'si' => 'EUR',
        'lu' => 'EUR',
        'mt' => 'EUR',
        'mc' => 'EUR',
        'sm' => 'EUR',
        'ad' => 'EUR',
        'me' => 'EUR',
        'xk' => 'EUR',
        'au' => 'AUD',
        'jp' => 'JPY',
        'in' => 'INR',
        'id' => 'IDR',
        'nl' => 'EUR',
        'pl' => 'PLN',
        'ua' => 'UAH',
        'ru' => 'RUB',
        'tr' => 'TRY',
        'cz' => 'CZK',
        'kz' => 'KZT',
        'ch' => 'CHF',
        'li' => 'CHF',
        'no' => 'NOK',
        'dk' => 'DKK',
        'hu' => 'HUF',
        'hr' => 'HRK',
        'is' => 'ISK',
        'rs' => 'RSD',
        'ba' => 'BAM',
        'mk' => 'MKD',
        'al' => 'ALL',
        'nz' => 'NZD',
        'sg' => 'SGD',
        'hk' => 'HKD',
        'my' => 'MYR',
        'th' => 'THB',
        'sa' => 'SAR',
        'lk' => 'LKR',
        'ph' => 'PHP',
        'pk' => 'PKR',
        'ar' => 'ARS',
        'co' => 'COP',
        'cl' => 'CLP',
        'vn' => 'VND',
        'il' => 'ILS',
        'kr' => 'KRW',
        'cn' => 'CNY',
        'br' => 'BRL',
        'mx' => 'MXN',
        'za' => 'ZAR',
    ],

];